-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE fs_category (
    id SERIAL PRIMARY KEY,
    name text NOT NULL UNIQUE,
    main_category boolean NOT NULL DEFAULT false
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX fs_category_pkey ON fs_category(id int4_ops);
CREATE INDEX fs_category_name ON fs_category(name text_ops);
CREATE UNIQUE INDEX fs_category_name_key ON fs_category(name text_ops);
