-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE fs_category_relationship (
    fs_category_parent_id integer REFERENCES fs_category(id) ON DELETE CASCADE,
    fs_category_child_id integer REFERENCES fs_category(id) ON DELETE CASCADE,
    CONSTRAINT fs_category_relationship_pkey PRIMARY KEY (fs_category_parent_id, fs_category_child_id)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX fs_category_relationship_pkey ON fs_category_relationship(fs_category_parent_id int4_ops,fs_category_child_id int4_ops);
CREATE INDEX fs_category_relationship_child_id_idx ON fs_category_relationship(fs_category_child_id int4_ops);
